spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc: DEBUG
