spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/testdbspringboot
    username: root
    password: Mysql@13579

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc: DEBUG
